[package]
name = "data_structs"
version = "0.1.0"
authors = ["Stacks-Mamba <stexor12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
